import closeIcon from "../icons/close.svg?raw";
import searchIcon from "../icons/search.svg?raw";
import { svgIconUrl } from "./svg-icon.js";
import { configureCookbookStates } from "./tasty-states.js";
import { defineComponent } from "../define-component.js";

configureCookbookStates();

export const SearchResultsRoot = defineComponent("SearchResults", {
  as: "div",
  "data-tasty-anatomy": "SearchResults",
  styles: {
    display: "flex",
    flow: "column",
    flexGrow: "1",
    minBlockSize: "0",
    "$pagefind-ui-primary": "#accent-text",
    "$pagefind-ui-text": "#text-soft",
    "$pagefind-ui-background": "#surface",
    "$pagefind-ui-border": "#border",
    "$pagefind-ui-border-width": "$border-width",
    "$pagefind-ui-tag": "#surface-3",
    preset: "body",
    UI: {
      $: ".pagefind-ui, [data-search-results]",
      display: "flex",
      flow: "column",
      flexGrow: "1",
      minBlockSize: "0",
    },
    Form: {
      $: ".pagefind-ui__form",
      position: "relative",
      display: "flex",
      flow: "column",
      flexGrow: "1",
      minBlockSize: "0",
    },
    Field: {
      $: ".cookbook-search-field",
      position: "relative",
      flexShrink: "0",
    },
    EngineControls: {
      $: ".pagefind-ui__search-input, .pagefind-ui__search-clear",
      display: "none",
    },
    Drawer: {
      $: ".pagefind-ui__drawer",
      display: "flex",
      flow: "column",
      flexGrow: "1",
      minBlockSize: "0",
    },
    Input: {
      $: ".cookbook-search-input",
      flexShrink: "0",
      inlineSize: "100%",
      minBlockSize: "3rem",
      paddingInlineStart: "2.75rem",
      paddingInlineEnd: "2.75rem",
      color: "#text",
      border: true,
      radius: "$radius",
      fill: "#surface",
      borderColor: "#border",
      boxShadow: "none",
    },
    Clear: {
      $: ".cookbook-search-clear",
      position: "absolute",
      insetBlockStart: "0",
      insetInlineEnd: "0",
      inlineSize: "3rem",
      blockSize: "3rem",
      padding: "0",
      color: "#text-soft",
      border: "0",
      fill: "#clear",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "0",
      cursor: "pointer",
    },
    Results: {
      $: ".pagefind-ui__results-area",
      flexGrow: "1",
      minBlockSize: "0",
      overflowY: "auto",
      marginBlockStart: { "": "($gap * 3)", "@mobile": "($gap * 2)" },
      borderBlockStart: "$border-width solid #border",
      inlineSize: { "@mobile": "(100% + ($gap * 4))" },
      inlineMargin: { "@mobile": "(-1 * $gap * 2)" },
      inlinePadding: { "@mobile": "($gap * 2)" },
      paddingBlockEnd: { "@mobile": "($gap * 2)" },
    },
    Result: {
      $: ".pagefind-ui__result",
      paddingBlockStart: "($gap * 2)",
      paddingBlockEnd: "($gap * 2)",
      borderBlockStart: "$border-width solid #border",
    },
    ResultLink: {
      $: ".pagefind-ui__result-link",
      color: "#text",
      preset: "strong",
    },
    Message: {
      $: ".pagefind-ui__message",
      color: "#text-soft",
      preset: "small",
    },
    List: {
      $: ".pagefind-ui__results",
      margin: "0",
      padding: "0",
      listStyle: "none",
    },
    Title: {
      $: ".pagefind-ui__result-title",
      margin: "0",
      preset: "body / strong",
    },
    Excerpt: {
      $: ".pagefind-ui__result-excerpt",
      margin: "$gap 0 0",
      color: "#text-soft",
      preset: "small",
    },
    NestedResult: {
      $: ".pagefind-ui__result-nested",
      margin: "2x 0 0",
      inlinePadding: "2x start",
      inlineBorder: "1bw solid #border start",
    },
    Match: {
      $: "mark",
      color: "#accent-surface-text",
      fill: "#accent-surface",
      preset: "strong",
      radius: "0.2em",
    },
    More: {
      $: ".pagefind-ui__button",
      display: { "@mobile": "block" },
      inlineSize: { "@mobile": "max-content" },
      marginInlineStart: { "@mobile": "auto" },
      padding: "1x 2x",
      border: true,
      radius: "$radius",
      color: "#text",
      fill: "#surface-2",
      preset: "navigation",
    },
    HoverMore: { $: ".pagefind-ui__button:hover", fill: "#surface-2-hover" },
    SearchIcon: {
      $: ".cookbook-search-field::before",
      content: '""',
      position: "absolute",
      zIndex: "1",
      insetBlockStart: "1rem",
      insetInlineStart: "1rem",
      display: "block",
      inlineSize: "1rem",
      blockSize: "1rem",
      fill: "#text-soft",
      mask: `url("${svgIconUrl(searchIcon)}") center / contain no-repeat`,
      pointerEvents: "none",
    },
    ClearIcon: {
      $: ".cookbook-search-clear::before",
      content: '""',
      display: "block",
      inlineSize: "1rem",
      blockSize: "1rem",
      fill: "#current",
      mask: `url("${svgIconUrl(closeIcon)}") center / 1rem no-repeat`,
    },
    SuppressedClear: {
      $: ".cookbook-search-clear[hidden]",
      display: "none",
    },
  },
});
