import { configureCookbookStates } from "./tasty-states.js";
import { tasty } from "@tenphi/tasty";
import { customizeComponent } from "./customize-component.js";

configureCookbookStates();

export const SidebarRoot = customizeComponent(
  "Sidebar",
  tasty({
    as: "cookbook-sidebar-pane",
    "data-tasty-anatomy": "Sidebar",
    styles: {
      "$sidebar-transition": "120ms",
      display: { "@desktop": "block" },
      visibility: { "": "visible", "@mobile": "hidden" },
      position: "fixed",
      zIndex: { "": "8", "@mobile": "12" },
      blockInset: { "": "$docs-nav-height start, 0 end", "@mobile": "0" },
      inlineInset: {
        "": "0 start, auto end",
        "@desktop":
          "max(0px, calc((100% - $layout-width) / 2)) start, auto end",
      },
      inlineSize: {
        "": "$sidebar-width",
        "@mobile": "min(22rem, calc(100% - 2rem))",
      },
      blockSize: "auto",
      margin: "0",
      padding: "0",
      border: "0",
      color: "#text",
      overflowY: "auto",
      scrollbarGutter: "stable",
      fill: "#surface",
      overscrollBehavior: "contain",
      shadow: { "": "none", "@mobile": "0.25rem 0 1rem #shadow" },
      translate: { "": "0", "@mobile": "-100% 0" },
      transition: {
        "": "none",
        "@mobile & !@reduced-motion":
          "translate $sidebar-transition ease-out, visibility $sidebar-transition, display $sidebar-transition allow-discrete, overlay $sidebar-transition allow-discrete",
      },
      Backdrop: {
        $: "&::backdrop",
        fill: "#overlay",
        opacity: "0",
        transition: {
          "": "none",
          "@mobile & !@reduced-motion":
            "opacity $sidebar-transition ease-out, display $sidebar-transition allow-discrete, overlay $sidebar-transition allow-discrete",
        },
      },
      OpenBackdrop: { $: "&:popover-open[data-open]::backdrop", opacity: "1" },
      MobileHeading: {
        $: ".td-sidebar-heading",
        display: "flex",
        hide: { "": true, "@mobile": false },
        alignItems: "center",
        justifyContent: "space-between",
        gap: "$gap",
      },
      HomeLink: {
        $: ".td-sidebar-heading__home",
        display: "flex",
        alignItems: "center",
        textDecoration: "none",
        inlineSize: "min 0",
        padding: "0",
        gap: "$gap",
        color: "#text",
        preset: "h4",
      },
      HomeLogo: {
        $: '.td-sidebar-heading__home > [data-tasty-anatomy="Logo"]',
        inlineSize: "2rem",
        blockSize: "2rem",
      },
      HomeLabel: {
        $: ".td-sidebar-heading__home > [data-site-title]",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
      },
      Close: {
        $: ".td-sidebar-heading > button",
        display: "grid",
        placeItems: "center",
        flexShrink: "0",
        inlineSize: "$docs-menu-button-size",
        blockSize: "$docs-menu-button-size",
        padding: "0",
        border: "0",
        color: "#text-soft",
        fill: "#clear",
        radius: "$header-control-radius",
      },
      HoverClose: {
        $: ".td-sidebar-heading > button:hover",
        color: "#text",
        fill: "#surface-2-hover",
      },
      CloseIcon: {
        $: ".td-sidebar-heading > button > svg",
        inlineSize: "1.25rem",
        blockSize: "1.25rem",
      },
      CurrentLink: {
        $: 'cookbook-sidebar a[aria-current="page"], cookbook-sidebar a[aria-current="page"]:hover, cookbook-sidebar a[aria-current="page"]:focus',
        color: "#accent-text",
        fill: "#accent-surface-subtle",
        preset: "navigation / strong",
      },
      OpenPane: { $: "&:popover-open", visibility: { "@mobile": "visible" } },
      EnteredPane: {
        $: "&:popover-open[data-open]",
        translate: { "@mobile": "0" },
      },
      Content: {
        $: ".sidebar-content",
        display: "flex",
        flow: "column",
        minBlockSize: "100%",
        inlinePadding: "$docs-sidebar-pad-x",
        gap: "($gap * 2)",
        paddingBlockStart: { "": "($gap * 3)", "@mobile": "($gap * 2)" },
        paddingBlockEnd: "($gap * 6)",
      },
      Tree: { $: "cookbook-sidebar", display: "block" },
      List: {
        $: "cookbook-sidebar ul",
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr)",
        gap: "1bw",
        margin: "0",
        padding: "0",
        listStyle: "none",
      },
      Item: { $: "cookbook-sidebar li", overflowWrap: "anywhere" },
      TopLevelSpacing: { $: ".top-level > li + li", marginBlockStart: "0" },
      GroupSpacing: {
        $: ".top-level > li + li:has(> .sidebar-section-label)",
        marginBlockStart: "($gap * 2.5)",
      },
      NestedItem: {
        $: "cookbook-sidebar details > ul > li",
        marginInlineStart: "($gap * 1.5)",
      },
      SectionHeading: {
        $: ".sidebar-section-label",
        margin: "0 0 1bw",
        padding: "($gap * 0.75) ($gap * 1.25)",
        color: "#text",
        preset: "small / strong",
      },
      Control: {
        $: "cookbook-sidebar summary, cookbook-sidebar a",
        blockSize: "min 2.25rem",
        padding: "($gap * 0.75) ($gap * 1.25)",
        color: "#sidebar-text",
        preset: "navigation",
        radius: "$radius",
        textDecoration: "none",
      },
      Summary: {
        $: "cookbook-sidebar summary",
        blockMargin: "1bw end",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "1x",
        cursor: "pointer",
        userSelect: "none",
      },
      GroupLabel: {
        $: ".group-label",
        display: "flex",
        alignItems: "center",
        minInlineSize: "0",
        gap: "0.25em",
      },
      GroupLabelText: {
        $: ".group-label > span:first-child",
        minInlineSize: "0",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
      },
      Link: {
        $: "cookbook-sidebar a",
        inlineSize: "100%",
        display: "flex",
        alignItems: "center",
        minInlineSize: "0",
        gap: "0.25em",
        fill: "#surface",
        preset: "navigation",
      },
      LinkLabel: {
        $: "a > span:first-child",
        minInlineSize: "0",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
      },
      InteractiveControl: {
        $: "cookbook-sidebar a:hover, cookbook-sidebar a:focus-visible, cookbook-sidebar summary:hover, cookbook-sidebar summary:focus-visible",
        color: "#text",
        fill: "#surface-2-hover",
      },
      SummaryMarker: {
        $: "cookbook-sidebar summary::marker, summary::-webkit-details-marker",
        hide: true,
      },
      Caret: {
        $: ".sidebar-caret",
        flexShrink: "0",
        inlineSize: "1rem",
        blockSize: "1rem",
        // The pinned linter omits :dir(), which Tasty and the browser support.
        // eslint-disable-next-line tasty/valid-state-key
        transform: { "": "none", ":dir(rtl)": "rotate(180deg)" },
      },
      ExpandedCaret: {
        $: "details[open] > summary > .sidebar-caret, details[open] > summary > a > .sidebar-caret",
        transform: "rotate(90deg)",
      },
      LinkedSummary: { $: "summary:has(> a)", padding: "0" },
      GroupLink: { $: "summary > a", justifyContent: "space-between" },
      LinkedSectionHeading: {
        $: ".sidebar-section-label:has(> a)",
        padding: "0",
      },
      SectionLink: {
        $: '.sidebar-section-label > a:not([aria-current="page"])',
        color: "#text",
        preset: "small / strong",
      },
      Badge: {
        $: ".sidebar-badge",
        flexShrink: "0",
        padding: "0.125rem 0.375rem",
        color: "#text-soft",
        fill: "#surface-3",
        border: "$border-width solid #border",
        radius: "$radius",
        preset: "small",
      },
      TopLevelLink: {
        $: 'a.large:not([aria-current="page"])',
        color: "#sidebar-text",
        preset: "navigation",
      },
    },
  }),
);
