export default {
  tokens: [
    "$gap",
    "$radius",
    "$card-radius",
    "$border-width",
    "$outline-width",
    "$outline-offset",
    "$layout-width",
    "$content-width",
    "$sidebar-width",
    "$control-height",
    "#surface",
    "#surface-2",
    "#surface-3",
    "#surface-2-hover",
    "#surface-2-pressed",
    "#surface-3-hover",
    "#surface-3-pressed",
    "#text",
    "#text-soft",
    "#border",
    "#border-strong",
    "#accent-text",
    "#accent-surface",
    "#accent-surface-text",
    "#focus",
    "#shadow",
    "#overlay",
  ],
  units: ["x", "r", "cr", "bw"],
  presets: [
    "body",
    "heading",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "small",
    "code",
  ],
};
