import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    components: "src/components.ts",
    "components/props": "src/components/props.ts",
    "client/tabs": "src/client/tabs.ts",
    styling: "src/styling.ts",
    "eslint-plugin": "src/eslint-plugin.ts",
    localization: "src/localization.ts",
    navigation: "src/navigation.ts",
    versioning: "src/versioning.ts",
    "client/appearance": "src/client/appearance.ts",
    "client/code-copy": "src/client/code-copy.ts",
    "client/heading-links": "src/client/heading-links.ts",
    "client/search": "src/client/search.ts",
    "client/navigation": "src/client/navigation.ts",
    "client/sidebar": "src/client/sidebar.ts",
    "markdown/rendered-content": "src/markdown/rendered-content.ts",
    "theme/defaults": "src/theme/defaults.ts",
    "theme/tasty-config": "src/theme/tasty-config.ts",
  },
  format: "esm",
  fixedExtension: false,
  dts: true,
  sourcemap: true,
  clean: true,
  platform: "node",
  deps: {
    neverBundle: [
      /^astro(?:\/|$)/,
      /^@astrojs\//,
      /^@pagefind\//,
      /^@tenphi\//,
      /^react(?:\/|$)/,
      /\.astro$/,
    ],
  },
});
