import type { TastyValidationConfig } from "@tenphi/eslint-plugin-tasty";

export default {
  importSources: [
    "@tenphi/cookbook/styling",
    "@tenphi/renderer/styling",
    "./component-styles.js",
    "../define-component.js",
  ],
  styleFunctions: {
    defineComponent: { argument: 1, kind: "options" },
    extendComponent: { argument: 2, kind: "options", partial: true },
    resolveComponentStyles: { argument: 1, kind: "styles" },
    mergeStyles: { argument: "all", kind: "styles", partial: true },
  },
  tokens: [
    "$gap",
    "$radius",
    "$header-control-radius",
    "$card-radius",
    "$border-width",
    "$outline-width",
    "$outline-offset",
    "$layout-width",
    "$content-width",
    "$sidebar-width",
    "$control-height",
    "$transition",
    "$sharp-radius",
    "$bold-font-weight",
    "#white",
    "#black",
    "#clear",
    "#current",
    "#surface",
    "#header",
    "#heading",
    "#surface-2",
    "#surface-3",
    "#surface-2-hover",
    "#surface-2-pressed",
    "#surface-3-hover",
    "#surface-3-pressed",
    "#text",
    "#text-soft",
    "#text-muted",
    "#sidebar-text",
    "#border",
    "#border-strong",
    "#accent-text",
    "#accent-surface",
    "#accent-surface-text",
    "#logo-surface",
    "#logo-mark",
    "#accent-surface-subtle",
    "#accent-surface-2-subtle",
    "#focus",
    "#shadow",
    "#overlay",
    "#syntax-bg",
    "#syntax-text",
    "#syntax-comment",
    "#syntax-punctuation",
    "#syntax-keyword",
    "#syntax-string",
    "#syntax-token",
    "#syntax-property",
    "#syntax-number",
    "#syntax-function",
    "#syntax-value",
    "#syntax-operator",
    "#info",
    "#info-surface",
    "#info-text",
    "#success",
    "#success-surface",
    "#success-text",
    "#warning",
    "#warning-surface",
    "#warning-text",
    "#danger",
    "#danger-surface",
    "#danger-text",
    "#orange-surface",
    "#orange",
    "#orange-text",
    "#green-surface",
    "#green",
    "#green-text",
    "#blue-surface",
    "#blue",
    "#blue-text",
    "#purple-surface",
    "#purple",
    "#purple-text",
    "#red-surface",
    "#red",
    "#red-text",
  ],
  units: ["x", "r", "cr", "bw"],
  states: [
    "@system-light",
    "@system-dark",
    "@light",
    "@dark",
    "@mobile",
    "@desktop",
    "@small",
    "@compact",
    "@shell-mobile",
    "@shell-desktop",
    "@narrow-layout",
    "@medium-layout",
    "@reduced-motion",
  ],
  presets: [
    "body",
    "heading",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "navigation",
    "small",
    "code",
  ],
} satisfies TastyValidationConfig;
